version: '3.9'

services:

  db_server:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: testy
    ports:
      - 3306:3306

  db_admin:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - db_server
    ports:
      - 9000:8080

  backend:
    image: yilmazchef/testy-backend
    depends_on:
      - db_server
      - db_admin
    links:
      - db_server:db_server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_server:3306/database?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSOWRD: testy
    ports:
      - 8001:8080

